/* AI Influencer's catalog arrives in English; these are its labels in Spanish.
   A label the platform adds later falls back to its English text. */
const ES: Record<string, string> = {
  Gender: "Género", Female: "Mujer", Male: "Hombre", "Trans man": "Hombre trans", "Trans woman": "Mujer trans",
  "Non-binary": "No binario",
  Ethnicity: "Etnia", African: "Africana", "East Asian": "Asiática oriental", European: "Europea", Indian: "India",
  "Middle Eastern": "Medio Oriente", "Latin American": "Latinoamericana",
  Age: "Edad", Adult: "Adulto", Mature: "Maduro", Senior: "Mayor",
  "Skin tone": "Tono de piel", Porcelain: "Porcelana", Fair: "Muy clara", Light: "Clara", Olive: "Oliva",
  Tan: "Bronceada", Brown: "Morena", "Deep brown": "Morena oscura", Ebony: "Ébano",
  Height: "Altura", Average: "Promedio", Tall: "Alto", "Very tall": "Muy alto", Short: "Bajo",
  "Body type": "Tipo de cuerpo", Build: "Complexión", Slim: "Delgado", Athletic: "Atlético", Muscular: "Musculoso",
  Curvy: "Curvilíneo", Heavy: "Robusto", "Ultra muscular": "Ultra musculoso",
  "Big glutes, wide hips": "Glúteos grandes, caderas anchas", "Human centaur": "Centauro humano",
  Proportions: "Proporciones", "Long limbs": "Extremidades largas", "Short legs": "Piernas cortas",
  "Broad shoulders": "Hombros anchos", "Tiny waist": "Cintura muy fina", "Egg body": "Cuerpo de huevo",
  "Pot belly": "Barriga",
  "Eye color": "Color de ojos", Black: "Negro", Hazel: "Avellana", Green: "Verde", Blue: "Azul",
  "Ice blue": "Azul hielo", Amber: "Ámbar", Grey: "Gris",
  "Eye shape": "Forma de ojos", Almond: "Almendrados", Round: "Redondos", Hooded: "Encapotados", Monolid: "Monopárpado",
  Upturned: "Hacia arriba", Downturned: "Hacia abajo", "Close-set": "Juntos", "Wide-set": "Separados",
  Asymmetric: "Asimétricos", Large: "Grandes", "Extra large": "Muy grandes",
  "Head shape": "Forma de la cabeza", "Oval face": "Cara ovalada", "Round face": "Cara redonda",
  "Square face": "Cara cuadrada", "Heart-shaped face": "Cara de corazón", "Long face": "Cara alargada",
  "Small head": "Cabeza pequeña", "Large forehead": "Frente grande", "Early-human features": "Rasgos primitivos",
  "Strong jaw": "Mandíbula marcada", "Large chin": "Barbilla grande", "Wide square jaw": "Mandíbula ancha y cuadrada",
  "Facial features": "Rasgos faciales", Freckles: "Pecas", Dimples: "Hoyuelos", "High cheekbones": "Pómulos altos",
  "Full lips": "Labios carnosos", "Thick eyebrows": "Cejas gruesas", "Beauty mark": "Lunar",
  "Rounded nose": "Nariz redondeada", "Upturned nose": "Nariz respingada", "Pointed nose": "Nariz puntiaguda",
  "Small nose": "Nariz pequeña", "Pouty lips": "Labios de puchero", "Small mouth": "Boca pequeña",
  "Wide mouth": "Boca ancha", Unibrow: "Uniceja", "Thin high eyebrows": "Cejas finas y altas",
  "Bushy eyebrows": "Cejas pobladas", "Prominent ears": "Orejas prominentes", "Asymmetric ears": "Orejas asimétricas",
  "Gap teeth": "Dientes separados", "Prominent front teeth": "Dientes frontales salidos",
  "Rosy cheeks": "Mejillas sonrosadas", "Pointed chin": "Barbilla puntiaguda",
  "Long straight eyebrows": "Cejas largas y rectas", "Flat cheekbones": "Pómulos planos",
  "Receding chin": "Barbilla retraída", "Long chin": "Barbilla larga", "High forehead": "Frente alta",
  "Under-eye bags": "Ojeras",
  Neck: "Cuello", "Average neck": "Cuello normal", "Wide column neck": "Cuello ancho", "Long neck": "Cuello largo",
  "Short neck": "Cuello corto",
  Hairstyle: "Peinado", Bald: "Calvo", "Short hair": "Pelo corto", "Long hair": "Pelo largo", "Buzz cut": "Rapado",
  "Bowl cut": "Corte de tazón", Mullet: "Mullet", Braids: "Trenzas", Pigtails: "Coletas", Afro: "Afro",
  "Punk hairstyle": "Peinado punk", "Pompadour wave": "Tupé", "Hair horns": "Cuernos de pelo",
  "Soft-serve swirl": "Remolino de helado", "Beehive tower": "Colmena alta", "Curl sphere": "Esfera de rizos",
  "Mouse-ear puffs": "Moños de ratón", "Lampshade bob": "Bob de lámpara", "Hair wings": "Alas de pelo",
  "Hedgehog spikes": "Pinchos de erizo", "Bald + side tufts": "Calvo con mechones laterales",
  "Perm dome": "Cúpula de permanente", "Curly flat-top block": "Bloque rizado plano", "Bat-wing bowl": "Tazón ala de murciélago",
  "Handlebar hair": "Pelo manubrio", "Baroque wig": "Peluca barroca", "Stair steps": "Escalones",
  "Shelf bob": "Bob en repisa", "Twin corkscrews": "Dos tirabuzones", "Side coil": "Espiral lateral",
  "Mushroom bowl": "Hongo",
  Style: "Estilo", "Hair color": "Color de pelo", "Hair colour": "Color de pelo", "Jet black": "Negro azabache",
  "Dark brown": "Castaño oscuro", Chestnut: "Castaño", Ginger: "Pelirrojo", Blonde: "Rubio", Platinum: "Platino",
  White: "Blanco", "Pastel pink": "Rosa pastel", Lilac: "Lila", Red: "Rojo",
  "Facial hair": "Vello facial", "Clean-shaven": "Afeitado", Stubble: "Barba de días", "Full beard": "Barba completa",
  Goatee: "Perilla", Moustache: "Bigote", "Pencil moustache": "Bigote fino", "Handlebar moustache": "Bigote de manubrio",
  "Push-broom moustache": "Bigote cepillo", "Braided beard": "Barba trenzada",
  "Distinctive features": "Rasgos distintivos", Heterochromia: "Heterocromía", "Face tattoo": "Tatuaje en la cara",
  "Septum ring": "Piercing en el septum", "Stacked ear piercings": "Varios piercings en la oreja",
  "Eyebrow slits": "Cortes en la ceja", "Bleached brows": "Cejas decoloradas", "No eyebrows": "Sin cejas",
  "Gold grill": "Grill de oro", Braces: "Brackets", "Scar across the brow": "Cicatriz en la ceja",
  "Face gems": "Gemas en la cara", "Elf ears": "Orejas de elfo", "Extra-long lashes": "Pestañas muy largas",
  "Nose bandage": "Curita en la nariz",
  Retro: "Retro", Sporty: "Deportivo", Y2K: "Y2K", Theatre: "Teatral", Goth: "Gótico", Suits: "De traje",
  Streetstyle: "Urbano", Casual: "Casual", Aesthetic: "Estética",
  Accessories: "Accesorios", None: "Ninguno", Glasses: "Lentes", Headphones: "Audífonos", Jewelry: "Joyas",
  Hat: "Sombrero", Bag: "Bolso",
};

export function influencerLabel(label: string): string {
  return ES[label] ?? label;
}
